resource-room/media-release/_posts/2021-11-19-file-presidents-challenge-2021-appreciation-event-media-release.md
=> update Media release

pages/terms-of-use.md
Hi Min Yan, 
I am updating the URL stated in the page. The URL should not be http://www.pc.org.sg
=> Update file: terms-of-use.md

_config.yml, _data/footer.yml, index.md
Hi Bryan, 
I am adding FB Pixel and GA4 for PC website.
=> Linking FB Pixel and GA4 accounts

_links/forms.md, index.md
/files/Grant%20Call/pc2024_application_form.pdf
=> Update of PC Grant Form Link 

_who-we-are/what-we-do.md, index.md, pages/WhatWeDo.md, pages/who-we-support.md
Found the reason why the donate page is not reflecting.
=> Take Action - Donate Page

index.md
Isomer has fixed the issue for the homepage. 
We are now able to update homepage
=> Broken Link for HomePage

pages/who-we-support.md
Law Society Pro Bono Services has rebranded as Pro Bono SG. 
Updated the new name and new url - https://www.ncss.gov.sg/social-service-agencies/membership/list-of-ncss-members#
Email reference from Pro Bono SG
------------------------------------
From: Madeline Phang <madeline.phang@probono.sg> 
Sent: Wednesday, 29 March 2023 9:35 am
To: NCSS Support (NCSS) <NCSS_Support@ncss.gov.sg>
Cc: PBSG Comms <comms@probono.sg>
Subject: Important Update - Our Company's Rebranding [Pro Bono SG]
Dear NCSS,
I am Madeline from Pro Bono SG. I hope this email finds you well. As you may know, Law Society Pro Bono Services has rebranded as Pro Bono SG. 
As part of this rebranding, we have a new logo and a new website URL. Our new name reflects the commitment of all Singaporeans, Singaporean residents and …
=> Updates to Law Society Pro Bono Services

pages/who-we-support.md
Minor error on - All Saints Home
=> President's Challenge 2024 - Benefitting Agencies and Media Release

index.md
https://www.sgenable.sg/your-first-stop/hiring-employment/employers/pledge
=> Broken Link Fix on homepage

_who-we-are/What We Do.md
Adding title parameter to YouTube Video
=> WOGAA fixes

_config.yml
Dear Bryan, 
Shermaine has added the coding for tracking pixels. 
For your in-system approval, please. 
Thank you.
=> Tracking Pixel

_data/navigation.yml, _take-action/donate.md, _take-action/partner-with-us.md, _who-we-are/What We Do.md, _who-we-are/milestones.md, pages/faq.md
Update mentions of PC to President's Challenge. Remove mentions of PCELF.
=> Update PC Copy

_who-we-are/milestones.md
PO clarified to replace the 2024 writeup instead of updating as additional content.
=> Milestones

_who-we-are/About President's Challenge.md
=> About President's Challenge

pages/who-we-support.md
Updated the featured service user from Ganesh to Aziz, to align with social post.
=> Updated service user feature under Who We Support

_config.yml, pages/contact-us.md
Changed to hyperlink from google map to onemap (https://www.onemap.gov.sg/?lat=1.3122144&lng=103.7897232)
=> DSA 2024 Feedback - UC30

_data/footer.yml
Nor Hayati created a form link with the new logo. 
https://form.gov.sg/6837c4b2dc33a3a315fb65ce
They are working to unpublish the old form.
=> Update of Feedback Form Link

_our-fellowship-programmes/Civic Action Fellowship.md, _our-fellowship-programmes/Institute of Technical Education (ITE) Inspire.md
Civic Action Fellowship
Institute of Technical Education (ITE) Inspire
=> Updates to Fellowship Pages

index.md
Updated link from /take-action/ to  /take-action/donate/
=> Update broken link for Make A Difference tab

_our-fellowship-programmes/President’s Challenge Fellow (Civic Action).md, _our-fellowship-programmes/President’s Challenge Fellow (ITE Inspire).md, _our-fellowship-programmes/President’s Challenge Fellow (Springboard).md
WR-20250725-0003
WR-20250730-0001
=> Updates to President’s Challenge Fellowship pages
